# Preprocessing dataset: ATP Tennis Rankings, Results, and Stats
## Source: https://github.com/JeffSackmann/tennis_atp
### Predictive modeling. Master in Big Data Analysis. 2018/2019
### Authors: Francisco J. Lozano, Antonio Miranda, Diego Su√°rez

In [25]:
import pandas as pd
import numpy as np
import warnings
from tqdm import tqdm
warnings.filterwarnings('ignore')
data = pd.concat([pd.read_csv("data/atp_matches_2016.csv"),pd.read_csv("data/atp_matches_2017.csv")])
data.iloc[0]

tourney_id                2016-M020
tourney_name               Brisbane
surface                        Hard
draw_size                        32
tourney_level                     A
tourney_date            2.01601e+07
match_num                       300
winner_id                    105683
winner_seed                       4
winner_entry                    NaN
winner_name            Milos Raonic
winner_hand                       R
winner_ht                       196
winner_ioc                      CAN
winner_age                  25.0212
winner_rank                      14
winner_rank_points             2170
loser_id                     103819
loser_seed                        1
loser_entry                     NaN
loser_name            Roger Federer
loser_hand                        R
loser_ht                        185
loser_ioc                       SUI
loser_age                   34.4066
loser_rank                        3
loser_rank_points              8265
score                       6-4 6-4
best_of                           3
round                             F
minutes                          87
w_ace                             6
w_df                              6
w_svpt                           60
w_1stIn                          34
w_1stWon                         28
w_2ndWon                         14
w_SvGms                          10
w_bpSaved                         1
w_bpFaced                         1
l_ace                             7
l_df                              3
l_svpt                           61
l_1stIn                          34
l_1stWon                         25
l_2ndWon                         14
l_SvGms                          10
l_bpSaved                         3
l_bpFaced                         5
Name: 0, dtype: object

- tourney_id. A character id that uniquely identifies each tournament
- tourney_name. A character tournament name
- surface. A character description of the court surface (Carpet, Clay, Grass, or Hard)
- draw_size. A numeric value indicating the draw size
- tourney_level. A character description of the tournament level (A, C, D, F, G, M)
- match_num. A numeric indicating the order of matches
- winner_id. A numeric id identifying the player who won the match
- winner_seed. A numeric value for the winner's seeding
- winner_entry. A character value indicating the winner's entry type (WC = Wild card, Q = Qualifier, LL = Lucky loser, or PR = Protected ranking)
- winner_name. A character of the winner's name
- winner_hand. A character value indicated the handedness of the winner
- winner_ht. A numeric value of the winner's height in cm
- winner_ioc. A character of the winner's country of origin
- winner_age. A numeric of the winner's age at the time of the match
- winner_rank. A numeric of the winner's rank at the time of the match
- winner_rank_points. A numeric of the winner's 52-week ranking points at the time of the match
- loser_id. A numeric id identifying the player who won the match
- loser_seed. A numeric value for the loser's seeding
- loser_entry. A character value indicating the loser's entry type (WC = Wild card, Q = Qualifier, LL = Lucky loser, or PR = Protected ranking)
- loser_name. A character of the loser's name
- loser_hand. A character value indicated the handedness of the loser
- loser_ht. A numeric value of the loser's height in cm
- loser_ioc. A character of the loser's country of origin
- loser_age. A numeric of the loser's age at the time of the match
- loser_rank. A numeric of the loser's rank at the time of the match
- loser_rank_points. A numeric of the loser's 52-week ranking points at the time of the match
- score. A character of the match score
- best_of. A numeric value indicating the match format (3 or 5)
- round. A character indicating the round of the match
- minutes. A numeric value for the duration of the match in minutes
- w_ace. A numeric value for the winner's number of aces
- w_df. A numeric value for the winner's number of double faults
- w_svpt. A numeric value for the winner's number of service points
- w_1stIn. A numeric value for the winner's number of first serves in
- w_1stWon. A numeric value for the winner's number of first service points won
- w_2ndWon. A numeric value for the winner's number of second service points won
- w_SvGms. A numeric value for the winner's number of service games
- w_bpSaved. A numeric value for the winner's number of breakpoints saves
- w_bpFaced. A numeric value for the winner's number of breakpoints faced
- l_ace. A numeric value for the loser's number of aces
- l_df. A numeric value for the loser's number of double faults
- l_svpt. A numeric value for the loser's number of service points
- l_1stIn. A numeric value for the loser's number of first serves in
- l_1stWon. A numeric value for the loser's number of first service points won
- l_2ndWon. A numeric value for the loser's number of second service points won
- l_SvGms. A numeric value for the loser's number of service games
- l_bpSaved. A numeric value for the loser's number of breakpoints saves
- l_bpFaced. A numeric value for the loser's number of breakpoints faced

In [26]:
"Number of rows: " + str(data.shape[0])

'Number of rows: 5890'

In [27]:
data.isnull().sum()

tourney_id              63
tourney_name            63
surface                 63
draw_size               63
tourney_level           63
tourney_date            63
match_num               63
winner_id               63
winner_seed           3309
winner_entry          5224
winner_name             63
winner_hand             67
winner_ht             1422
winner_ioc              63
winner_age              71
winner_rank             96
winner_rank_points      96
loser_id                63
loser_seed            4476
loser_entry           4802
loser_name              63
loser_hand              80
loser_ht              1912
loser_ioc               63
loser_age               78
loser_rank             147
loser_rank_points      147
score                   63
best_of                 63
round                   63
minutes                135
w_ace                  120
w_df                   120
w_svpt                 120
w_1stIn                120
w_1stWon               120
w_2ndWon               120
w_SvGms                120
w_bpSaved              120
w_bpFaced              120
l_ace                  120
l_df                   120
l_svpt                 120
l_1stIn                120
l_1stWon               120
l_2ndWon               120
l_SvGms                120
l_bpSaved              120
l_bpFaced              120
dtype: int64

In [28]:
new_data = data.drop(["winner_seed", "winner_entry", "winner_ht",
                      "loser_seed", "loser_entry", "loser_ht"], axis=1).dropna()

In [29]:
"Number of rows: " + str(new_data.shape[0])

'Number of rows: 5606'

Firstly, we need to get rid of information of winner and losers from columns as set it as a new column (label). To do it, we are going to set as player 1, the one as higher ranking, and the second player as the one with lower ranking

In [30]:
new_data["p1_win"] = True
new_columns = [col.replace("winner_","p1_").replace("w_","p1_").replace("loser_","p2_").replace("l_","p2_")
               for col in new_data.columns]
new_data.columns = new_columns
", ". join(new_columns)

'tourney_id, tourney_name, surface, drap1_size, tourney_level, tourney_date, match_num, p1_id, p1_name, p1_hand, p1_ioc, p1_age, p1_rank, p1_rank_points, p2_id, p2_name, p2_hand, p2_ioc, p2_age, p2_rank, p2_rank_points, score, best_of, round, minutes, p1_ace, p1_df, p1_svpt, p1_1stIn, p1_1stWon, p1_2ndWon, p1_SvGms, p1_bpSaved, p1_bpFaced, p2_ace, p2_df, p2_svpt, p2_1stIn, p2_1stWon, p2_2ndWon, p2_SvGms, p2_bpSaved, p2_bpFaced, p1_win'

In [31]:
p1_stats_columns = ["p1_id", "p1_name", "p1_hand", "p1_ioc", "p1_age", "p1_rank", "p1_rank_points",
                    "p1_ace", "p1_df", "p1_svpt", "p1_1stIn", "p1_1stWon", "p1_2ndWon", "p1_SvGms",
                    "p1_bpSaved", "p1_bpFaced"]
p2_stats_columns = ["p2_id", "p2_name", "p2_hand", "p2_ioc", "p2_age", "p2_rank", "p2_rank_points",
                    "p2_ace", "p2_df", "p2_svpt", "p2_1stIn", "p2_1stWon", "p2_2ndWon", "p2_SvGms",
                    "p2_bpSaved", "p2_bpFaced"]

for idx, match in new_data.iterrows():
    if match["p1_rank"] > match["p2_rank"]:
        #Swap player
        new_data.loc[idx, "p1_win"] = False
        p1_stats = new_data.loc[idx, p1_stats_columns]
        new_data.loc[idx, p1_stats_columns] = new_data.loc[idx, p2_stats_columns].values
        new_data.loc[idx, p2_stats_columns] = p1_stats.values

In [32]:
new_data.loc[0]

,tourney_id,tourney_name,surface,drap1_size,tourney_level,tourney_date,match_num,p1_id,p1_name,p1_hand,...,p2_ace,p2_df,p2_svpt,p2_1stIn,p2_1stWon,p2_2ndWon,p2_SvGms,p2_bpSaved,p2_bpFaced,p1_win
0,2016-M020,Brisbane,Hard,32.0,A,20160104.0,300.0,105683.0,Milos Raonic,R,...,7.0,3.0,61.0,34.0,25.0,14.0,10.0,3.0,5.0,False
0,2017-M020,Brisbane,Hard,32.0,A,20170102.0,300.0,105777.0,Grigor Dimitrov,R,...,4.0,0.0,69.0,49.0,36.0,9.0,12.0,2.0,5.0,False

We add a new label for creating a regression problem: Difference in points

In [33]:
new_data.loc[:, "diff_points"] =\
    abs((new_data["p1_1stWon"] + new_data["p1_2ndWon"]) - (new_data["p2_1stWon"] + new_data["p1_2ndWon"]))

Now, we sort the dataset by date yo have our stats dataset ready to explore. We will get 5-matches and 20-matches
rolling statistics for each player to construct the final dataset

In [34]:
new_data = new_data.sort_values(by=["tourney_date", "match_num"], ascending=True).reset_index(drop=True)

In [35]:
new_data[["tourney_name", "tourney_date", "match_num", "p1_name", "p2_name"]].head(5)

,tourney_name,tourney_date,match_num,p1_name,p2_name
0,Doha,20160104.0,270.0,Rafael Nadal,Pablo Carreno Busta
1,Brisbane,20160104.0,271.0,Denis Istomin,Mikhail Kukushkin
2,Chennai,20160104.0,271.0,Ramkumar Ramanathan,Daniel Gimeno Traver
3,Doha,20160104.0,271.0,Aslan Karatsev,Robin Haase
4,Brisbane,20160104.0,272.0,Dusan Lajovic,Radek Stepanek

In [36]:
", ".join(new_data.columns)

'tourney_id, tourney_name, surface, drap1_size, tourney_level, tourney_date, match_num, p1_id, p1_name, p1_hand, p1_ioc, p1_age, p1_rank, p1_rank_points, p2_id, p2_name, p2_hand, p2_ioc, p2_age, p2_rank, p2_rank_points, score, best_of, round, minutes, p1_ace, p1_df, p1_svpt, p1_1stIn, p1_1stWon, p1_2ndWon, p1_SvGms, p1_bpSaved, p1_bpFaced, p2_ace, p2_df, p2_svpt, p2_1stIn, p2_1stWon, p2_2ndWon, p2_SvGms, p2_bpSaved, p2_bpFaced, p1_win, diff_points'

In [37]:
# A priori stats
a_priori_columns = ['tourney_id', 'tourney_name', 'surface', 'drap1_size', 'tourney_level', 'tourney_date', 'match_num',
                    'p1_id', 'p1_name', 'p1_hand', 'p1_ioc', 'p1_age', 'p1_rank', 'p1_rank_points',
                    'p2_id', 'p2_name', 'p2_hand', 'p2_ioc', 'p2_age', 'p2_rank', 'p2_rank_points']
final_dataset = new_data[a_priori_columns].copy()

In [38]:
def get_players_stats(new_data, match_id, window_sizes):
    stats = {}
    match = new_data.loc[match_id]
    
    # Get windows for player 1 and player 2 (unbounded yet)
    mask_p1 = (new_data.index < match_id) & ((new_data.p1_id == match.p1_id) | (new_data.p2_id == match.p1_id))
    p1_window = new_data[mask_p1]
    p1_window.loc[:, "p2_win"] = ~p1_window.loc[:, "p1_win"].values
    mask_p2 = (new_data.index < match_id) & ((new_data.p1_id == match.p2_id) | (new_data.p2_id == match.p2_id))
    p2_window = new_data[mask_p2]
    p2_window.loc[:, "p2_win"] = ~p2_window.loc[:, "p1_win"].values
    
    # Set stats for windows
    stats_columns = ["id", "name", "hand", "ioc", "age", "rank", "rank_points",
                     "ace", "df", "svpt", "1stIn", "1stWon", "2ndWon", "SvGms",
                     "bpSaved", "bpFaced","win"]
    p1_window_stats = pd.DataFrame(index=p1_window.index, columns=stats_columns)
    p1_window_stats.loc[p1_window[match.p1_id == p1_window.p1_id].index,:]= \
        p1_window.loc[match.p1_id == p1_window.p1_id, map(lambda x: "p1_"+x, stats_columns)].values
    p1_window_stats.loc[p1_window[match.p1_id == p1_window.p2_id].index,:]= \
        p1_window.loc[match.p1_id == p1_window.p2_id, map(lambda x: "p2_"+x, stats_columns)].values
    
    p2_window_stats = pd.DataFrame(index=p2_window.index, columns=stats_columns)
    p2_window_stats.loc[p2_window[match.p2_id == p2_window.p1_id].index,:]= \
        p2_window.loc[match.p2_id == p2_window.p1_id, map(lambda x: "p1_"+x, stats_columns)].values
    p2_window_stats.loc[p2_window[match.p2_id == p2_window.p2_id].index,:]= \
        p2_window.loc[match.p2_id == p2_window.p2_id, map(lambda x: "p2_"+x, stats_columns)].values
    
    for window_size in window_sizes:
        # Stats for player 1
        p1_last_matches = p1_window_stats.tail(window_size)
        if p1_last_matches.empty:
            stats["p1_win_prob_{}w".format(window_size)] = np.nan
            stats["p1_ace_prob_{}w".format(window_size)] = np.nan
            stats["p1_df_prob_{}w".format(window_size)] = np.nan
            stats["p1_svptWon_prob_{}w".format(window_size)] = np.nan
            #stats["p1_bpSaved_prob_{}w".format(window_size)] = np.nan
        else:
            # Get Percetage of matches won in last windows_size matches
            stats["p1_win_prob_{}w".format(window_size)] = p1_last_matches.win.sum() / p1_last_matches.shape[0]
            # Get percentage of aces/point served in last windows_size matches (aces / svpt)
            stats["p1_ace_prob_{}w".format(window_size)] = p1_last_matches.ace.sum() / p1_last_matches.svpt.sum()
            # Get percentage of double faults/point served in last windows size matches (df / svpt)
            stats["p1_df_prob_{}w".format(window_size)] = p1_last_matches.df.sum() / p1_last_matches.svpt.sum()
            # Get percentage of points won/point served in last windows size matches ((1stWon + 2ndWon) / svpt)
            stats["p1_svptWon_prob_{}w".format(window_size)] = \
                (p1_last_matches["1stWon"] + p1_last_matches["2ndWon"]).sum() / p1_last_matches.svpt.sum()
            # Get percentage of breakpoint saved (bpSaved / bpFaced)
            #stats["p1_bpSaved_prob_{}w".format(window_size)] = p1_last_matches.bpSaved.sum() / p1_last_matches.bpFaced.sum()

        # Stats for player 2
        p2_last_matches = p2_window_stats.tail(window_size)
        if p2_last_matches.empty:
            stats["p2_win_prob_{}w".format(window_size)] = np.nan
            stats["p2_ace_prob_{}w".format(window_size)] = np.nan
            stats["p2_df_prob_{}w".format(window_size)] = np.nan
            stats["p2_svptWon_prob_{}w".format(window_size)] = np.nan
            #stats["p2_bpSaved_prob_{}w".format(window_size)] = np.nan
        else:
            # Get Percetage of matches won in last windows_size matches
            stats["p2_win_prob_{}w".format(window_size)] = p2_last_matches.win.sum() / p2_last_matches.shape[0]
            # Get percentage of aces/point served in last windows_size matches (aces / svpt)
            stats["p2_ace_prob_{}w".format(window_size)] = p2_last_matches.ace.sum() / p2_last_matches.svpt.sum()
            # Get percentage of double faults/point served in last windows size matches (df / svpt)
            stats["p2_df_prob_{}w".format(window_size)] = p2_last_matches.df.sum() / p2_last_matches.svpt.sum()
            # Get percentage of points won/point served in last windows size matches ((1stWon + 2ndWon) / svpt)
            stats["p2_svptWon_prob_{}w".format(window_size)] = \
                (p2_last_matches["1stWon"] + p2_last_matches["2ndWon"]).sum() / p2_last_matches.svpt.sum()
            # Get percentage of breakpoint saved (bpSaved / bpFaced)
            #stats["p2_bpSaved_prob_{}w".format(window_size)] = p2_last_matches.bpSaved.sum() / p2_last_matches.bpFaced.sum()

        # Get Percentage of matches won in surface in last windows_size matches (played in that surface)
        p1_surface_matches = p1_window_stats.loc[new_data.loc[p1_window_stats.index, "surface"] == match.surface].tail(window_size)
        if p1_surface_matches.empty:
            stats["p1_surface_win_prob_{}w".format(window_size)] = pd.np.nan
        else:
            stats["p1_surface_win_prob_{}w".format(window_size)] = \
                p1_surface_matches.win.sum() / p1_surface_matches.shape[0]
        p2_surface_matches = p2_window_stats.loc[new_data.loc[p2_window_stats.index, "surface"] == match.surface].tail(window_size)
        if p2_surface_matches.empty:
            stats["p2_surface_win_prob_{}w".format(window_size)] = pd.np.nan
        else:
            stats["p2_surface_win_prob_{}w".format(window_size)] = \
                p2_surface_matches.win.sum() / p2_surface_matches.shape[0]

    return pd.Series(stats)

In [39]:
match_id = 2760-1
get_players_stats(new_data, match_id, [20])

p1_win_prob_20w            0.850000
p1_ace_prob_20w            0.126904
p1_df_prob_20w             0.038434
p1_svptWon_prob_20w        0.689630
p2_win_prob_20w            0.700000
p2_ace_prob_20w            0.066336
p2_df_prob_20w             0.024179
p2_svptWon_prob_20w        0.642901
p1_surface_win_prob_20w    0.850000
p2_surface_win_prob_20w    0.700000
dtype: float64

In [42]:
window_sizes = [20] 
new_stats = []
for idx, match in tqdm(new_data.iterrows()):
    new_stats.append(get_players_stats(new_data, idx, window_sizes))
pd.DataFrame(new_stats)

5606it [3:16:46,  1.48it/s]

,p1_win_prob_20w,p1_ace_prob_20w,p1_df_prob_20w,p1_svptWon_prob_20w,p2_win_prob_20w,p2_ace_prob_20w,p2_df_prob_20w,p2_svptWon_prob_20w,p1_surface_win_prob_20w,p2_surface_win_prob_20w
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
5576,0.500000,0.123810,0.041905,0.654603,0.800000,0.106942,0.052533,0.653533,0.450000,0.80
5577,0.700000,0.032805,0.016402,0.610169,0.450000,0.082393,0.030474,0.645598,0.700000,0.55
5578,0.125000,0.082852,0.030829,0.595376,0.750000,0.168580,0.045921,0.672508,0.200000,0.75
5579,0.550000,0.061159,0.025751,0.634657,0.550000,0.052599,0.048215,0.631183,0.550000,0.40
5580,0.350000,0.050960,0.050960,0.614163,0.900000,0.060876,0.024624,0.715458,0.300000,0.90
5581,0.600000,0.106911,0.050756,0.667387,0.700000,0.089120,0.053241,0.646412,0.600000,0.65
5582,0.450000,0.064821,0.041536,0.660793,0.600000,0.079812,0.039645,0.661450,0.450000,0.55
5583,0.850000,0.151185,0.039718,0.678411,0.750000,0.038462,0.031805,0.661243,0.750000,0.75
5584,0.450000,0.092008,0.056414,0.642713,0.900000,0.095176,0.029987,0.679270,0.450000,0.85
5585,0.700000,0.238825,0.033206,0.712005,0.800000,0.116556,0.050331,0.691391,0.700000,0.80
5586,0.750000,0.106184,0.021237,0.675203,0.450000,0.121136,0.044164,0.656782,0.750000,0.40
5587,0.111111,0.077586,0.029310,0.603448,0.450000,0.081574,0.031945,0.641187,0.166667,0.55
5588,0.900000,0.057026,0.024440,0.709437,0.550000,0.052300,0.047889,0.632640,0.900000,0.40
5589,0.450000,0.067288,0.039973,0.661559,0.700000,0.088585,0.055291,0.639715,0.400000,0.65
5590,0.850000,0.144371,0.043046,0.665563,0.450000,0.097120,0.056932,0.649699,0.750000,0.40
5591,0.650000,0.232242,0.033972,0.708462,0.750000,0.108073,0.020182,0.679688,0.650000,0.75
5592,0.700000,0.085645,0.056092,0.636912,0.500000,0.099791,0.055129,0.640614,0.700000,0.40
5593,0.200000,0.080916,0.027481,0.609160,0.700000,0.225707,0.033825,0.716482,0.285714,0.70
5594,0.700000,0.086562,0.054479,0.638015,0.181818,0.084306,0.025940,0.626459,0.700000,0.25
5595,0.800000,0.104332,0.051861,0.643075,0.750000,0.089382,0.054589,0.646071,0.800000,0.75
5596,0.850000,0.147901,0.041972,0.668221,0.900000,0.125860,0.027510,0.712517,0.750000,0.90
5597,0.600000,0.077766,0.039144,0.653967,0.900000,0.088599,0.032967,0.670330,0.550000,0.90
5598,0.700000,0.031008,0.019678,0.606440,0.850000,0.117147,0.050393,0.700262,0.700000,0.85
5599,0.900000,0.129913,0.027315,0.712858,0.900000,0.082517,0.035664,0.669930,0.900000,0.90
5600,0.850000,0.114381,0.051505,0.698997,0.750000,0.088411,0.054958,0.637993,0.850000,0.75
5601,0.900000,0.085592,0.034237,0.673324,0.850000,0.108911,0.050825,0.695710,0.900000,0.85
5602,0.850000,0.085417,0.035417,0.665278,0.600000,0.106011,0.051366,0.665027,0.850000,0.60
5603,0.400000,0.042774,0.020739,0.604666,0.650000,0.131547,0.033496,0.690621,0.550000,0.65
5604,0.850000,0.087695,0.033311,0.669613,0.650000,0.132064,0.033784,0.691032,0.850000,0.65
5605,0.550000,0.104794,0.050725,0.655518,0.350000,0.041746,0.021505,0.597090,0.550000,0.55

In [46]:
pd.concat([final_dataset, pd.DataFrame(new_stats), new_data[["p1_win", "diff_points"]].astype(int)], axis=1).to_csv("atp_matches_with_stats_2016_17.csv", index=False)

In [ ]:
## Columns description
- tourney_id. A character id that uniquely identifies each tournament
- tourney_name. A character tournament name
- surface. A character description of the court surface (Carpet, Clay, Grass, or Hard)
- draw_size. A numeric value indicating the draw size
- tourney_level. A character description of the tournament level (A, C, D, F, G, M)
- tourney_date. A numeric indicating the starting date of the tourney.
- match_num. A numeric indicating the order of matches
- p1_id. A numeric id identifying the player with higher ranking
- p1_name. A character of the player with higher ranking's name
- p1_hand. A character value indicated the handedness of the player with higher ranking
- p1_ioc. A character of the player with higher ranking's country of origin
- p1_age. A numeric of the player with higher ranking's age at the time of the match
- p1_rank. A numeric of the player with higher ranking's rank at the time of the match
- p1_rank_points. A numeric of the winner's 52-week ranking points at the time of the match
- p2_id. A numeric id identifying the player with higher ranking
- p2_name. A character of the player with lower ranking's name
- p2_hand. A character value indicated the handedness of the player with higher ranking
- p2_ioc. A character of the player with lower ranking's country of origin
- p2_age. A numeric of the player with lower ranking's age at the time of the match
- p2_rank. A numeric of the player with lower ranking's rank at the time of the match
- p2_rank_points. A numeric of the lower's 52-week ranking points at the time of the match
- p1_win_prob_20w: Percentage of matches won by the player with higher ranking in the last 20 matches
- p1_ace_prob_20w: Percentage of aces by service done by the player with higher ranking in the last 20 matches
- p1_df_prob_20w: Percentage of double faults by service done by the player with higher ranking in the last 20 matches
- p1_svptWon_prob_20w: Percentage of services won by the player with higher ranking in the last 20 matches
- p2_win_prob_20w: Percentage of matches won by the player with lower ranking in the last 20 matches
- p2_ace_prob_20w: Percentage of aces by service done by the player with lower ranking in the last 20 matches
- p2_df_prob_20w: Percentage of double faults by service done by the player with lower ranking in the last 20 matches
- p2_svptWon_prob_20w: Percentage of services won by the player with lower ranking in the last 20 matches
- p1_surface_win_prob_20w: Percentage of matches won by the player with higher ranking in the last 20 matches played in the same surface
- p2_surface_win_prob_20w: Percentage of matches won by the player with higher ranking in the last 20 matches played in the same surface
- p1_win: If the player with higher ranking won the match (1)
- diff_points: Number of difference in services points won by each player